### ISSUE TITLE
登录只支持上百请求

### ISSUE THREAD

**Issue by decisive-strike** [ChanphongGu/ChatServer#1]
我查了一下，mysql8.0默认的最大连接数是151，你的图上也显示只能150个并发登录，你改改这个最大连接数应该能支持更高的并发量

**Comment by ChanphongGu** [comment]
> 我查了一下，mysql8.0默认的最大连接数是151，你的图上也显示只能150个并发登录，你改改这个最大连接数应该能支持更高的并发量

这个问题已经解决啦，最新代码还没更新上来，是由于频繁创建和销毁连接的原因，后改用数据库连接池了。你的方法也能一定程度改善并发。

**Comment by decisive-strike** [comment]
> > 我查了一下，mysql8.0默认的最大连接数是151，你的图上也显示只能150个并发登录，你改改这个最大连接数应该能支持更高的并发量
> 
> 这个问题已经解决啦，最新代码还没更新上来，是由于频繁创建和销毁连接的原因，后改用数据库连接池了。你的方法也能一定程度改善并发。

该用连接池之后，登录操作能做到1w级的并发吗

**Comment by ChanphongGu** [comment]
> > > 我查了一下，mysql8.0默认的最大连接数是151，你的图上也显示只能150个并发登录，你改改这个最大连接数应该能支持更高的并发量
> > 
> > 
> > 这个问题已经解决啦，最新代码还没更新上来，是由于频繁创建和销毁连接的原因，后改用数据库连接池了。你的方法也能一定程度改善并发。
> 
> 该用连接池之后，登录操作能做到1w级的并发吗

yes
